#cloud-config


runcmd:
  - yum install yum-utils -y
  - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - yum install docker-ce docker-ce-cli containerd.io -y 
  - systemctl enable docker
  - systemctl start docker
  - docker run -d --restart unless-stopped -p 80:80 -p 443:443 -v flexify:/var/opt/flexify/ flexifyio/ce
  - yum update -y

power_state:
  delay: "now"
  mode: reboot
  message: Bye Bye
  timeout: 30
  condition: True

final_message: "The system is finally up, after $UPTIME seconds, with Flexify"